### ISSUE TITLE
Zphisher error

### ISSUE THREAD

**Issue by anonymous-6969** [Bhaviktutorials/Termux-Megapackage#2]
It's showing error in negrok installing 
It's saying install negrok manually

**Comment by kdcloverkid** [comment]
https://github.com/Bhaviktutorials/Termux-Megapackage/issues/2#issue-742252476

**Comment by kdcloverkid** [comment]
Idk wht im doing

**Comment by kdcloverkid** [comment]
Hmmm

**Comment by Bhaviktutorials** [comment]
It's showing error because the tool(zphisher) was updated and it requires manual installation on ngrok you just have to download ngrok and extract into zphisher folder and run 
Or 
You can use shark tool it works better
